In [2]:
import pandas as pd
import json
df = pd.read_csv('deardata.csv')

In [3]:
def parse_text(row):
    t = json.loads(row[5])
    s = ''
    for item in t:
        s+=item['content']
    return s

df['doc'] = df.apply(parse_text, axis=1)
df.head()

,week,title,author,visual_img,legend_img,text,doc
0,1,Week 01: A week of clocks,Giorgia,01_Giorgia_DearData_01_Front.jpg,01_Giorgia_DearData_01_Back.jpg,"[{""header"": ""The topic:"", ""content"": "" This wa...",This was the first week of Dear Data – I was ...
1,1,Week 01: A week of clocks,Stefanie,01_Stefanie_DearData_01+front.jpg,01_Stefanie_DearData_01+back.jpg,"[{""header"": ""Data-gathering:"", ""content"": "" Or...",Originally Giorgia and I thought that we woul...
2,2,Week 02: A week of public transportation,Giorgia,02_Giorgia_DearData_02_Front.jpg,02_Giorgia_DearData_02_Back.jpg,"[{""header"": ""Data gathering:"", ""content"": "" Th...",This week I collected data on my walks and tr...
3,2,Week 02: A week of public transportation,Stefanie,02_Stefanie_DearData_02+front.jpg,02_Stefanie_DearData_02+back.jpg,"[{""header"": ""Data-gathering:"", ""content"": "" La...",Last week’s intensive data gathering means th...
4,3,Week 03: A week of thank yous,Giorgia,03_Giorgia_DearData_03_Front.jpg,03_Giorgia_DearData_03_Back.jpg,"[{""header"": ""The topic:"", ""content"": "" This we...","This week we wanted to see how kind we are, a..."

In [53]:
# word frequency
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words("english"))
stop_words = stop_words.union(["’", "‘", "“"])

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\namwk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [55]:
# create a word set without stop words
wset = gset = sset = set()
wdoc = gdoc = sdoc = ''

for index, row in df.iterrows():
    db = TextBlob(row['doc'])
    ws = set(db.words)
    wdoc+=row['doc']
    wset = wset.union(ws)
    if row['author']=='Giorgia':
        gset = gset.union(ws)
        gdoc += row['doc']
    else:
        sset = sset.union(ws)   
        sdoc += row['doc']
        
wset = wset-stop_words
gset = gset-stop_words
sset = sset-stop_words

wb = TextBlob(wdoc)
wdic = {}
for word in wset:    
    wdic[word]=wb.word_counts[word]

gb = TextBlob(gdoc)
gdic = {}
for word in gset:    
    gdic[word]=gb.word_counts[word]

sb = TextBlob(sdoc)
sdic = {}
for word in sset:    
    sdic[word]=sb.word_counts[word]
    
    
wdf = pd.DataFrame.from_dict({'word':list(wdic.keys()), 'count':list(wdic.values())})
                              
wdf.sort_values('count', ascending=False)

# love, friends, drawing, data,

                word  count
1991            data    606
5903            week    528
775             time    263
3935            like    239
2784           would    238
986             also    221
4854            card    209
5688             one    203
5534         drawing    185
4735          people    175
1901        postcard    155
1052             new    145
6112           think    144
2059               ”    141
3569            much    141
594           really    140
4912             way    136
5949            many    135
785            every    122
899             know    119
6491          little    118
134        different    116
5744            even    111
504             love    110
6567             see    107
1175         friends    107
869        something    103
3408            dear    103
564          project    102
324             work    100
...              ...    ...
5216            LOVE      0
2231         data.Oh      0
2239   Anti-Squirrel      0
5204   bartenderWhat      0
2250            Many      0
2251          Sneeze      0
5198         Penguin      0
2169         it.Even      0
2167            'and      0
5251      lives.This      0
2122             Yet      0
5291         Italian      0
5290             Dog      0
2116             Day      0
2117         Another      0
5284         Amazing      0
5283       goodbye.I      0
2121              's      0
5281             Don      0
5279              NO      0
2164           These      0
5276          Social      0
5274         Instead      0
5273  music-wise.But      0
2133        life.And      0
2142          Really      0
2150            HATE      0
5261              TV      0
2154            Draw      0
5356        Birdsong      0

[6685 rows x 2 columns]

In [56]:
gdf = pd.DataFrame.from_dict({'word':list(gdic.keys()), 'count':list(gdic.values())})
                              
gdf.sort_values('count', ascending=False)

# people, boyfriend, friends, drawing, data, week, time, us, work

                word  count
1328            data    289
3879            week    275
521             time    170
667             also    142
1373               ”    140
1843           would    139
3747             one    107
1270        postcard    104
714              new     99
2606            like     94
528            every     92
3123          people     86
2263            dear     79
3910            many     75
2378            much     74
398           really     71
4242          little     69
3237             way     67
3782            even     67
339             love     66
2516       boyfriend     63
3653         drawing     62
610             know     62
3149            kind     58
1716            ones     58
85         different     57
794          friends     57
4006           think     56
3696              us     55
216             work     54
...              ...    ...
3555         so.This      0
1308         DRESSES      0
3490         Italian      0
1445           These      0
3448       Dear-Data      0
3413         notes.I      0
1436            Draw      0
1433            HATE      0
3418      drawings.I      0
3422    nervous.This      0
1420        life.And      0
3427         Penguin      0
1412              's      0
3433   bartenderWhat      0
1398       Different      0
3443            LOVE      0
3450        worlds.I      0
3489             Dog      0
1370              OF      0
1369            Mela      0
3464      lives.This      0
3470              TV      0
3478  music-wise.But      0
3480          Social      0
3482              NO      0
3483             Don      0
3484       goodbye.I      0
3485         Amazing      0
1331           Since      0
1326      level.This      0

[4363 rows x 2 columns]

In [57]:
sdf = pd.DataFrame.from_dict({'word':list(sdic.keys()), 'count':list(sdic.values())})
                              
sdf.sort_values('count', ascending=False)
# people, husband, life, drawing, data, week, time

                word  count
1210            data    317
3644            week    253
2997            card    169
2417            like    145
3399         drawing    123
1705           would     99
3503             one     96
464             time     93
2919          people     89
3777           think     88
599             also     79
3169          though     74
3032             way     69
360           really     69
2189            much     67
1976  data-gathering     65
338          project     63
1262           quite     62
3672            many     60
2797           often     60
87         different     59
2667          always     59
2906            feel     58
3886         husband     58
543             know     57
4075             see     56
525        something     54
1135            life     53
272         tracking     51
1149        postcard     51
...              ...    ...
645              NSA      0
264             THEN      0
3633         Through      0
3058          Anyhow      0
3055          Centre      0
946       'purveyors      0
945              AND      0
3691            Does      0
1286           Ocean      0
1939             THE      0
3669         Luckily      0
3668      'screaming      0
3667            Aged      0
1275        'digital      0
1990          inAged      0
2478          go.But      0
1982            Here      0
1980    EMBARRASSING      0
1261  degree.However      0
2487          tint.I      0
288            Grows      0
1266   disgusting.So      0
627            There      0
285        Londoners      0
629     wake.Finally      0
3657            Will      0
1273            Fizz      0
1962            This      0
952           Ending      0
2759              ME      0

[4154 rows x 2 columns]

In [ ]:
# noun phrases frequency

In [59]:

print('Sentiment of Whole Reflection Text', wb.sentiment)

print("Sentiment of Giorgia's reflection", gb.sentiment)

print("Sentiment of Stefanie's reflection", sb.sentiment)

Sentiment of Whole Reflection Text Sentiment(polarity=0.13636683673051855, subjectivity=0.49552282246049584)
Sentiment of Giorgia's reflection Sentiment(polarity=0.15039792012086603, subjectivity=0.49388976447018323)
Sentiment of Stefanie's reflection Sentiment(polarity=0.12080923220283937, subjectivity=0.4970789692600997)